title = "Cours de Guitare à Genève et Lausanne"
# TO CHANGE
baseURL = "https://cryptodictionary.github.io" 
languageCode = "fr-FR"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Cours de guitare à Genève et Lausanne"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  body_classes = "avenir bg-white"
  favicon = ""
  site_logo = ""
  description = "TODO"
  facebook = "https://facebook.com/CoursDeGuitareLausanneEtGeneve"
  instagram = "https://instagram.com/cours_de_guitare.ch"
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  #background_color_class = "bg-moon-gray"
  recent_posts_number = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
